# Generated by Django 3.1.4 on 2021-04-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggos_only_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_picture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
